name: Push-to-EC2

on: push
jobs:
  deploy:
      name: Build JFrog Docker Image
      runs-on: ubuntu-latest

      steps:
        - name: Checkout the code
          uses: actions/checkout@v1
          
        - name: Make File
          run: echo $DOCKER_PASSWORD >my_password.txt && cat my_password.txt

        - name: List Repo files
          run: ls -l

        # - name: Build Docker image
        #   run: docker build -t test .

        # - name: Check images
        #   run: docker images
      
      # - name: Login to JFROG CLI
      #   run: jf config add $ARTIFACTORY_SERVER_ID --artifactory-url=$ARTIFACTORY_URL --basic-auth-only=true --user=$USER --password=$PASSWORD --interactive=false
        # docker tag <image name> ${server-name}.jfrog.io/{repo-name}/<image name>
        # docker push ${server-name}.jfrog.io/{repo-name}/<image name>
        # Testing
        - uses: jfrog/setup-jfrog-cli@v2
          env:
            JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
            DOCKER_USERNAME: ${{ secrets.docker_user }}
            DOCKER_PASSWORD: ${{ secrets.docker_pass }}
        - run: |
            # Ping the server
            jfrog rt ping
            # echo $DOCKER_PASSWORD >my_password.txt
            # cat my_password.txt
            # cat ~/my_password.txt | docker login --username engineer.ali91@live.com --password-stdin
            # docker login alisaeed.jfrog.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            echo "$env:DOCKER_PASSWORD" | docker login alisaeed.jfrog.io --username engineer.ali91@live.com --password-stdin
            docker build -t test .
            docker tag test alisaeed.jfrog.io/test-docker/test:latest
            docker images
            docker push alisaeed.jfrog.io/test-docker/test:latest
        
        
      
      # - name: Check the running containers
      #   run: docker ps

      # - name: Deploy to my EC2 instance
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
        
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     SOURCE: "./"
      #     REMOTE_HOST: ${{ secrets.HOST_DNS }}
      #     REMOTE_USER: ${{ secrets.USERNAME }}
      #     TARGET: "/home/ubuntu/autov1"
