name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        
      - name: List Repo files
        run: ls -l
        
      - name: Check Docker version
        run: docker -v
      
      - name: Build Docker image
        run: docker build -t test .
      
      - name: Check image
        run: docker images
        
      - name: Configuring artifactory
        uses: "jfrog/setup-jfrog-cli@v2"
      - name: Pushing artifactory
    env:
        with: 
            APIKEY: ${{secrets.JF_APIKEY}}
            
        run: |
          jf c add --url https://artifactory.xxxxxx.ae:443 --user alisaeed --password "$APIKEY"
          jf rt ping
          cd workspace
          sudo touch newfile.txt
          jf rt u newfile.txt github_actions_testing
      
      - name: Check the running containers
        run: docker ps

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
        
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ubuntu/autov1"
