name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        
      - name: List Repo files
        run: ls -l
        
      - name: Check Docker version
        run: docker -v
      
      - name: Build Docker image
        run: docker build -t test .
      
      - name: Check image
        run: docker images
        
      - name: Tag the image JFrog
        run: docker tag latest alisaeed.jfrog.io/test-docker/test:latest
        
      - name: Push to JFrog
        run: docker push alisaeed.jfrog.io/test-docker/test>:latest
      
      - name: Check the running containers
        run: docker ps

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
        
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ubuntu/autov1"
